### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by vinkla** [kbond/php-backup#11]
Is there any documentation anywhere?

**Comment by kbond** [comment]
I recently extracted this library from https://github.com/kbond/ZenstruckBackupBundle and haven't had time to document this standalone library yet. Are you using this in Symfony?

**Comment by vinkla** [comment]
Okay, I see. I wanted to try to use it with Laravel.

**Comment by vinkla** [comment]
What is the basics?

**Comment by vinkla** [comment]
Accidentally double closed and opened.

**Comment by vinkla** [comment]
What are the basics? Initialize a new class with a bunch of config?

**Comment by kbond** [comment]
Ah, ok, cool. First, you need to create a backup `Profile` - this requires:
1. Profile name
2. "Scratch directory" where to hold the temporary files
3. One or more `Sources` (where data to backup comes from - sql/files)
4. One or more `Destinations` (where the backup should go - directory/s3)
5. A `Processor` (how to combine the files into a single file - zip/gzip)
6. A `Namer` (what to name the single backup file)

``` php
$profile = new Profile(
    'my_backup',
    '/tmp/zenstruck-backup',
    new ZipArchiveProcessor('zip'),
    new TimestampNamer('timestamp'),
    [new MySqlDumpSource('database', 'database_name'), new RsyncSource('files', '/path/to/files')],
    [new StreamDestination('stream', '/path/to/backup/directory')]
);
```

Then you need to use the `Executor` to process the `Profile`.

``` php
(new Executor($psrLogger))->backup($profile);
```

**Comment by vinkla** [comment]
Okay, I'll try get something running. Thanks for helping out!

**Comment by kbond** [comment]
You can configure a console command as well - I'm not exactly sure how to add custom commands to laravel though.

``` php
$application = // ...
$application->add(new RunCommand());
$application->getHelperSet()->set(new BackupHelper(new ProfileRegistry([$profile], new Executor($psrLogger)));
```

You can now use the command:

```
zenstruck:backup:run my_backup
```

**Comment by vinkla** [comment]
Yeah, integrating the commands I know how to do. I'll try it out and come back if I've any other questions. I'm really grateful for your help!

**Comment by kbond** [comment]
No problem, I hope to get to documenting this library in the new year. If you get it working with Laravel, perhaps you could assist with a Laravel integration package.

**Comment by vinkla** [comment]
Yeah, that is my thinking. Many other backup libraries looks bad and I really like how well this package looks. I'll try making a Laravel integration once I get my current application's backup up and running.

**Comment by vinkla** [comment]
It works great! That was really easy to setup as well. Awesome work @kbond!

**Comment by kbond** [comment]
Awesome, glad to hear!

**Comment by vinkla** [comment]
I'll start on a Laravel integration asap.

**Comment by vinkla** [comment]
My Laravel package is coming along well. I've a question, why do we need to send a name to the profile? I see that we send a name to many classes, I'm curious why.

**Comment by kbond** [comment]
To distinguish between different profiles.

There is a `ProfileRegistry` that allows you to register 1 or more profiles. The console command uses this to be able to run different profiles:

```
zenstruck:backup:run <profile name>
```

**Comment by kbond** [comment]
The processors/namers/sources/destinations also each require a `name`. This allows you to register them with the `ProfileBuilder`, then call `ProfileBuilder::create()` with the names as parameters.

**Comment by vinkla** [comment]
Aah okay, I see. I will do something similar with the Laravel package. I call them connections. Will just use the connection name then. Thanks!

**Comment by kbond** [comment]
For the command, if you run it without a `<profile name>` it displays a table of your configured profiles and uses these names to show you how a profile is configured. Here is an example from a project of mine:

```
$ bin/console zenstruck:backup:run
Available Profiles:

+----------+-----------+----------+---------------------------------+--------------+
| Name     | Processor | Namer    | Sources                         | Destinations |
+----------+-----------+----------+---------------------------------+--------------+
| daily    | zip       | daily    | database, web_files, data_files | daily        |
| snapshot | zip       | snapshot | database, web_files, data_files | snapshot     |
+----------+-----------+----------+---------------------------------+--------------+
```

**Comment by kbond** [comment]
Are you going to be able to use the existing console commands in the laravel package? I know laravel uses the `symfony/console` component. I think I abstracted them enough to be used outside of the Symfony fullstack framework easily.

**Comment by vinkla** [comment]
Yeah, maybe. It should work.

**Comment by vinkla** [comment]
I'll create a first draft then we can take a look at it and see how we can improve it further.

**Comment by kbond** [comment]
Sounds good!

**Comment by vinkla** [comment]
Okay, here is a first draft https://github.com/vinkla/backup (haven't tested it yet). Let me know what you think.
