### ISSUE TITLE
Notification about fork

### ISSUE THREAD

**Issue by TheCelavi** [kbond/php-backup#12]
Hi Kevin,

I would like to inform you that we have re-designed your library in different repo: https://github.com/RunOpenCode/backup.

We have put our head into this library trying to re-imagine its architecture, and major changes which are BC break with your library are: 
- Usage of EventDispatcher and Workflow
- Support for incremental backups

We have tried to be fair as much as possible, keeping your credits where ever was possible:
1. README file within root dir of library
2. CREDITS file within root dir of library
3. In docblock of every single class of library.

We are not legal experts - if there is anything more that we have to do to provide you with credits, please tell us to do so.

If you want to claim ownership on our modification of your library - we are willing to cooperate.

Thank you.

**Comment by vinkla** [comment]
I think it is great you're reaching out. A lot of developers just copy and claim the rights without asking permission first. I'm not the owner or collaborator of this repository but I do know a little about the legal of repositories. The only thing I can see is that you guys need to keep the license file. You could name the license file `KBOND` with the license from this repo and a new `LICENSE` file with your license for your fork.

**Comment by kbond** [comment]
Hi Nikola,

No problem at all. The license is MIT so you are basically free to do what you want. I certainly appreciate the heads up though :)

For the LICENSE file (I'm no legal expert myself so I don't know if it required) you may want to do something similar to what I did: https://github.com/kbond/php-jwt/blob/master/LICENSE

That project is a fork of https://github.com/namshi/jose that I maintain.

Also, (again not required) is it possible for you to do an actual github fork of my repo so people can see the history? See my fork above or https://github.com/FriendsOfSymfony/FOSUserBundle for an example. _I know this is a little late now so if it is too much of a hassle don't worry about it._

I will keep an eye on your fork and see what can be pulled back upstream as you develop it.

This is what open source is all about!

--Kevin

**Comment by TheCelavi** [comment]
@vinkla Thank you for your suggestion, however, I did what Kevin requested. Nevertheless, since you uncover the fact that you do know about licenses - rest assured that I am going to bother you from now on! :D 

@kbond I am soooooooo sorry - I have started this from bare repo, I think that it is impossible now to make it as a fork easily. However, I will notify you when we implement something big (like new source or new destination) so you can review and take over, if you like to.

And, as I already said, If you want to take ownership of our repo, you can ask at any time - it is a standing offer.

Since this is resolved nicely - I am going to close this issue. Thanks guys!

**Comment by vinkla** [comment]
@TheCelavi haha, I don't know that much :smile: just had this issue with some of my packages.
